[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
marketplace = "Aj7N3Y3YVHbqDseY2WEBrkzAogcL5M1ezrTrsKU9M5Cs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ivmidable/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
